name: unit-test
run-name: Unit Test for goFIDOServer
on:
  pull_request:
    branches:
      - main
      - develop
jobs:
  unit-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ '1.20.x', '1.21.x' ]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}

      - name: go install
        run: go install

      - name: Test
        run: make test